receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlp/2:
    endpoint: data-prepper:21890
    tls:
      insecure: true
  debug:
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlp/2 ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug ]
